---
title: "Calculate GSVA with hall"
author: "Wei"
date: '2025-07-09'
output:
html_document: default
---

# 1. loading library and function
```{r}
suppressPackageStartupMessages(library(pacman))
pacman::p_load(tidyverse,ggpubr,rstatix,ggsci,ggsignif,reshape2)
suppressPackageStartupMessages(library(clusterProfiler))
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(writexl))
options(dplyr.summarise.inform = FALSE)

```

# 2. loading data
```{r}
# TPM
expr_data <- read_rds("/Users/xuewei/ZxProjects/LUAD/TCGA/01_Data/TCGA-LUAD.tpm_clinical.rds")
# Group
group_type <- read.table("/Users/xuewei/ZzzData/20250601_SPLC_MPLC_scRNA/01_preprocessing_v2/35_Metabolism_Lasso_Cox_v4/Rds_02_Lasso_Cox_04_risk_group_surv.txt", sep = "\t", h = T, check.names = F)
# Group all (Normal and Tumor)
Group_sample <- read_rds("/Users/xuewei/ZxProjects/LUAD/TCGA/01_Data/TCGA-LUAD.group_clinical.rds")

```


# 3. Data process
```{r}
expr_data <- expr_data %>% 
  rownames_to_column(var="sample")

Group_sample2 <- Group_sample %>% 
  select(sample, Group)

expr_data2 <- left_join(expr_data, Group_sample2, by = c("sample" = "sample"))

expr_data3 <- expr_data2 %>% 
  select(sample, Group, PGAM4, DLD, SRR, AGMAT, SRM, SMS, SMOX, P4HA1)


# expr_data <- as.data.frame(data.table::transpose(expr_data, keep.names = "Gene_symbol", make.names = 1)) %>% 
#   column_to_rownames(var="Gene_symbol")
# 
# # Group
# group_type <- group_type %>% 
#   select(sample_id, risk_group) %>% 
#   mutate(Status = str_replace_all(risk_group, "high_risk", "High")) %>% 
#   mutate(Status = str_replace_all(Status, "low_risk", "Low")) %>% 
#   select(sample_id, Status)
# 
# # Group_sample
# # Group_sample$pid <- substr(Group_sample$sample,1,15)
# join_sample_type <- Group_sample %>% 
#   select(sample)
# group_type2 <- semi_join(group_type, join_sample_type, by = c("sample_id" = "sample"))
# 
# Group_sample <- Group_sample %>% 
#   select(sample, Group) %>% 
#   column_to_rownames(var="sample")

```


# 6. calculate gene expression between low and high groups of all pathway signature genes
## 6.1 facet_wrap boxplot
```{r}
exp_boxplot <- expr_data3 %>% 
  gather(GeneSymbol, TPM, PGAM4:P4HA1)

exp_boxplot$Group = factor(exp_boxplot$Group, levels=c('Normal', 'Tumor'))

pdf("20250724_TCGA_exp_facet_wrap_full_v1.pdf",height=6,width=12)
ggplot(exp_boxplot, aes(x=Group, y=TPM, color=Group)) +
  facet_wrap(~GeneSymbol, nrow=2, strip.position = "top") +
  geom_boxplot(width=0.3)+
  geom_signif(comparisons = list(c("Normal", "Tumor")),
              map_signif_level = F,
              test = "wilcox.test",
              textsize=3,
              step_increase=0.1,
              color="#000000")+
  scale_y_continuous(expand = expansion(mult = c(0.05, 0.1)))+
  scale_fill_manual(values=c("#999999","#fdc4b6"))+
  scale_color_manual(values=c("#666666","#ca3e47"))+
  theme_minimal()+theme(legend.position="NA")+
  theme(strip.text = element_text(face="bold", color="#ca3e47", size=10))+
  theme(legend.title=element_blank())+
  labs(title = "TCGA-LUAD") +
  xlab(label = "")+ylab(label = "Expression log2(TPM+1)") +
  theme(panel.grid = element_blank(),axis.title = element_text(size = 15))+
  theme(axis.line=element_line(size=0.5,colour="black")) +
  theme(plot.title = element_text(hjust = 0.5, face="bold", color="black", size=15)) +
  theme(axis.ticks=element_line(size=0.5,colour="black"), axis.ticks.length=unit(0.5,"lines"))+
  theme(axis.text.x = element_text(face="bold", color="black", size=15),
        axis.text.y = element_text(face="bold", color="black", size=15),
        axis.title.x = element_text(face="bold", color="black", size=15),
        axis.title.y = element_text(face="bold", color="black", size=15))
dev.off()

```


## 6.2 PGAM4 expression between low and high groups
```{r}
boxplot_expr_PGAM4 <- expr_data3 %>% 
  select(sample, PGAM4, Group)
colnames(boxplot_expr_PGAM4)[colnames(boxplot_expr_PGAM4)=="PGAM4"] <- "FPKM"
summary(boxplot_expr_PGAM4[boxplot_expr_PGAM4$Group=="Normal",]$FPKM)
summary(boxplot_expr_PGAM4[boxplot_expr_PGAM4$Group=="Tumor",]$FPKM)
wilcox.test(boxplot_expr_PGAM4[boxplot_expr_PGAM4$Group=="Normal",]$FPKM,boxplot_expr_PGAM4[boxplot_expr_PGAM4$Group=="Tumor",]$FPKM)

```

```{r}
boxplot_expr_PGAM4$Group = factor(boxplot_expr_PGAM4$Group, levels=c('Normal', 'Tumor'))

pdf("20250724_TPM_PGAM4_boxplot_v1.pdf",height=5,width=5)
ggplot(boxplot_expr_PGAM4,aes(x=Group,y=FPKM,color=factor(Group)))+
  #geom_violin(width=0.45)+
  geom_boxplot(width=0.3)+
  scale_y_continuous(expand = ggplot2::expansion(mult = c(0.1, 0.1)))+
  #geom_quasirandom(width=0.1)+
  geom_signif(comparisons = list(c("Normal", "Tumor")),
              map_signif_level=F,
              textsize=6,test=wilcox.test,step_increase=0.1,color="#000000")+
  annotate("text", x=1.3, y=median(boxplot_expr_PGAM4[boxplot_expr_PGAM4$Group=="Normal",]$FPKM), label=sprintf("%0.2f", median(boxplot_expr_PGAM4[boxplot_expr_PGAM4$Group=="Normal",]$FPKM)), color = "#0f3a8a", size = 6)+
  annotate("text", x=2.3, y=median(boxplot_expr_PGAM4[boxplot_expr_PGAM4$Group=="Tumor",]$FPKM), label=sprintf("%0.2f", median(boxplot_expr_PGAM4[boxplot_expr_PGAM4$Group=="Tumor",]$FPKM)), color = "#ff6347", size = 6)+
  # scale_y_log10()+
  # ylim(0,6)+
  theme_classic()+theme(legend.position="NA")+
  # scale_fill_manual(values=c("#2ca9e1", "#e597b2"))+
  scale_color_manual(values=c("#0f3a8a", "#ff6347"))+
  labs(title = "PGAM4")+
  theme(panel.grid = element_blank(),axis.title = element_text(size = 15))+
  theme(plot.title = element_text(face="bold", color="black", size=20, hjust = 0.5))+
  xlab(label = NULL)+ylab(label = "Expression log2(TPM+1)")+
  theme(axis.line=element_line(size=0.5,colour="black"))+
  theme(axis.ticks=element_line(size=0.5,colour="black"),axis.ticks.length=unit(0.5,"lines"))+
  theme(axis.text.x = element_text(face="bold", color="black", size=15),
        axis.text.y = element_text(face="bold", color="black", size=15),
        axis.title.x = element_text(face="bold", color="black", size=15),
        axis.title.y = element_text(face="bold",color="black", size=15))
dev.off()

```

